package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/atjhoendz/notpushcation-service/internal/delivery/graphqlsvc/graph/generated"
	"github.com/atjhoendz/notpushcation-service/internal/model"
)

// CreateLiveBlogPosts is the resolver for the createLiveBlogPosts field.
func (r *mutationResolver) CreateLiveBlogPosts(ctx context.Context, input model.CreateLiveBlogPostInput) (bool, error) {
	r.LiveBlogPostUsecase.Create(input)
	return true, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
