package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/atjhoendz/notpushcation-service/internal/model"
	"github.com/kumparan/go-utils"
	log "github.com/sirupsen/logrus"
)

// PushNotificationBySegment is the resolver for the pushNotificationBySegment field.
func (r *mutationResolver) PushNotificationBySegment(ctx context.Context, input model.PushNotificationInput) (bool, error) {
	err := r.MessageProcessorUsecase.ProcessNotificationMessage(ctx, input)
	if err != nil {
		log.WithFields(log.Fields{
			"ctx":   utils.DumpIncomingContext(ctx),
			"input": input,
		}).Error(err)
		return false, err
	}
	return true, nil
}
